name: syllabuspu
description: PU syllabus

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  firebase_auth: ^1.1.4
  google_sign_in: ^5.0.2
  cloud_firestore: ^2.2.1
  dots_indicator: ^2.0.0
  flutter_native_splash: ^1.1.8+4
  flutter_signin_button: ^2.0.0
  animated_text_kit: ^4.2.1  




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - images/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

